version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  booking-service:
    image: gradle:7.6-jdk17
    container_name: booking-service-dev
    working_dir: /home/gradle/project
    volumes:
      - ./booking:/home/gradle/project:rw
    command: ["./gradlew", "bootRun", "--no-daemon"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    depends_on:
      - db

  notification-service:
    image: gradle:7.6-jdk17
    container_name: notification-service-dev
    working_dir: /home/gradle/project
    volumes:
      - ./notification:/home/gradle/project:rw
    command: ["./gradlew", "bootRun", "--no-daemon"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  db-data:
